assert_nothing_raised(${1:Exception}) { ${2} }
